AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'exe/**'
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['\#.*'] # ignore long comments

Metrics/MethodLength:
  Max: 20

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/MethodParameterName:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
